name: "Sample React CD Pipeline"

on:
    workflow_run:
       workflows: ["Sample React CI Pipeline"]
       types:
        - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Download product-ready build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          
      
      - name: "Clone the Repository"
        uses: actions/checkout@v4

      - name: "Check node version"
        run: node --version
      
      - name: "List Directories-Before"
        run: ls

      - name: "Installing Dependencies"
        run: npm install
      
      - name: "List Directories -After"
        run: ls
      
      - name: "Run Linting"
        run: npm run lint
        
      - name: "Run Tests"
        run: npm run test
      
      - name: "Run Build"
        run: npm run build

      - name: "Check Build Directory"
        run: ls -al ./dist/

      - name: "Upload product-ready build files"
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./dist

  
        
