name: "Sample React CD Pipeline"

on:
    workflow_run:
       workflows: ["Sample React CI Pipeline"]
       types:
        - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod_React CICD Pipeline

    steps:
      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      
      - name: "Setup vercel CLI"
        run: npm install -g vercel
    

      - name: "Download product-ready build files"
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          run-id: ${{github.event.workflow_run.id}}
          github-token: ${{github.token}}

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VIRCELTOKENREACT }} --yes 

