name: "Sample React CD Pipeline"

on:
    workflow_run:
       workflows: ["Sample React CI Pipeline"]
       types:
        - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod_React CICD Pipeline

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      
      - name: "Setup vercel CLI"
        run: npm install -g vercel
    
      - name: "Install Dependencies"
        run: npm install

      - name: "Download product-ready build files"
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          run-id: ${{github.event.workflow_run.id}}
          github-token: ${{github.token}}
          path: ./dist 

      - name: "List downloaded files (Debug)"
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Dist directory contents:"
          ls -la ./dist || echo "Dist directory not found"

      - name: "Deploy to Vercel"
        run: |
          # Deploy the current directory (Vercel will build automatically)
          vercel --prod \
            --token=${{ secrets.VIRCELTOKENREACT }} \
            --yes
            